name: Check workflow

on: "*"

jobs:

  perl-versions:
    runs-on: ubuntu-latest
    name: 'perl-versions default'
    steps:
      - uses: actions/checkout@v4
      - name: "uses perl-versions"
        id: action
        uses: ./

  since-v5.20:
    runs-on: ubuntu-latest
    name: 'since v5.20'

    steps:
      - uses: actions/checkout@v4
      - name: "uses perl-versions"
        id: action
        uses: ./
        with:
          since-perl: v5.20

  since-5.20:
    runs-on: ubuntu-latest
    name: 'since 5.20'

    steps:
      - uses: actions/checkout@v4
      - name: "uses perl-versions"
        id: action
        uses: ./
        with:
          since-perl: 5.20

  check:
    needs:
      - perl-versions
      - since-v5.20
      - since-5.20
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ fromJson (needs.perl-versions.outputs.perl-versions) }}"
