name: 'Perl versions'
description: 'Generate Perl versions list for your matrix'
inputs:
  since-perl:
    description: "List all Perl versions since this (including this). Example: 5.10"
    type: string
    default: "5.14"
  with-devel:
    description: "Whether to include also 'devel' Perl"
    type: boolean
    default: false
outputs:
  perl-versions:
    description: "JSON containing list of perl versions"
runs:
  using: "node20"
  main: "dist/index.js"
